In [12]:
# Loading the dataset using pandas

import pandas as pd
import numpy as np
import matplotlib.pylot as plt
import seaborn as sns

advisors = pd.read_csv(r'C:\Users\eitha\Downloads\BankingDomainDataAnalyticsProject\investment-advisiors.csv')

In [18]:
tables = {
    "clients": clients,
    "relationships": relationships,
    "gender": gender,
    "advisors": advisors
}

for name, df in tables.items():
    print(f"\n{name.upper()} DATA")
    display(df.head()) 
    df.info()

CLIENTS DATA

,Client ID,Name,Age,Location ID,Joined Bank,Banking Contact,Nationality,Occupation,Fee Structure,Loyalty Classification,...,Bank Deposits,Checking Accounts,Saving Accounts,Foreign Currency Account,Business Lending,Properties Owned,Risk Weighting,BRId,GenderId,IAId
0,IND81288,Raymond Mills,24,34324,06/05/2019,Anthony Torres,American,Safety Technician IV,High,Jade,...,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,1,1,1
1,IND65833,Julia Spencer,23,42205,10/12/2001,Jonathan Hawkins,African,Software Consultant,High,Jade,...,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,2,1,2
2,IND47499,Stephen Murray,27,7314,25/01/2010,Anthony Berry,European,Help Desk Operator,High,Gold,...,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,3,2,3
3,IND72498,Virginia Garza,40,34594,28/03/2019,Steve Diaz,American,Geologist II,Mid,Silver,...,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,4,1,4
4,IND60181,Melissa Sanders,46,41269,20/07/2012,Shawn Long,American,Assistant Professor,Mid,Platinum,...,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,1,2,5

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Client ID                 3000 non-null   str
 1   Name                      3000 non-null   str
 2   Age                       3000 non-null   int64
 3   Location ID               3000 non-null   int64
 4   Joined Bank               3000 non-null   str
 5   Banking Contact           3000 non-null   str
 6   Nationality               3000 non-null   str
 7   Occupation                3000 non-null   str
 8   Fee Structure             3000 non-null   str
 9   Loyalty Classification    3000 non-null   str
 10  Estimated Income          3000 non-null   float64
 11  Superannuation Savings    3000 non-null   float64
 12  Amount of Credit Cards    3000 non-null   int64
 13  Credit Card Balance       3000 non-null   float64
 14  Bank Loans                3000 non-null   float64
 15  Bank Deposits             3000 non-null   float64
 16  Checking Accounts         3000 non-null   float64
 17  Saving Accounts           3000 non-null   float64
 18  Foreign Currency Account  3000 non-null   float64
 19  Business Lending          3000 non-null   float64
 20  Properties Owned          3000 non-null   int64
 21  Risk Weighting            3000 non-null   int64
 22  BRId                      3000 non-null   int64
 23  GenderId                  3000 non-null   int64
 24  IAId                      3000 non-null   int64
dtypes: float64(9), int64(8), str(8)
memory usage: 586.1 KB

RELATIONSHIPS DATA

   BRId Banking Relationship
0     1               Retail
1     2        Institutional
2     3         Private Bank
3     4           Commercial

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   BRId                  4 non-null      int64
 1   Banking Relationship  4 non-null      str
dtypes: int64(1), str(1)
memory usage: 196.0 bytes

GENDER DATA

   GenderId  Gender
0         1    Male
1         2  Female

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   GenderId  2 non-null      int64
 1   Gender    2 non-null      str
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

ADVISORS DATA

   IAId Investment Advisor
0     1        Victor Dean
1     2      Jeremy Porter
2     3      Ernest Knight
3     4          Eric Shaw
4     5          Kevin Kim

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   IAId                22 non-null     int64
 1   Investment Advisor  22 non-null     str
dtypes: int64(1), str(1)
memory usage: 484.0 bytes